brew "ctags"
brew "vim"
brew "ack"
brew "htop"
brew "reattach-to-user-namespace"
brew "cmake"
brew "fzf"
brew "nvm"
brew "the_silver_searcher"

brew 'redis', restart_service: true
brew 'imagemagick'

cask "caffeine"
cask "dropbox"
cask "iterm2"
cask "skype"
cask "flux"
cask "firefox"
cask "google-chrome"
cask "harvest"
cask "heroku-toolbelt"
cask "sequel-pro"
cask "steam"
cask "virtualbox"
cask "slack"
cask "transmission"
cask "vlc"
cask "multibit"
cask "carbon-copy-cloner"
