#!/bin/bash

# create shell aliases for most used git commands
alias st='git st'
alias ci='git ci'
alias lg='git log'
alias co='git co'
alias br='git branch'
alias dc='git diff --cached'

alias add='git add --all'
alias log='git log'
alias push='git push'
alias pull='git pull'
alias stash='git stash'
alias clone='git clone'
alias fetch='git fetch'
alias merge='git merge -s recursive -X patience'
alias branch='git branch'
alias rebase='git rebase'
alias amend='git commit -C HEAD --amend'

alias up="git up"

alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vimrc"

# Pass aliases to root account
alias sudo='sudo '

if command -v reattach-to-user-namespace > /dev/null; then
  alias vim="reattach-to-user-namespace vim"
  alias mvim="reattach-to-user-namespace mvim"
fi

if ls --color -d . &> /dev/null; then
  alias ls='ls --color=tty' || alias ls='ls -G'
fi

if ls --group-directories-first &> /dev/null; then
  alias ls='ls --group-directories-first'
fi

if ls --color=tty --group-directories-first &> /dev/null; then
  alias ls='ls --color=tty --group-directories-first'
fi
