#!/bin/bash

# create shell aliases for most used git commands
alias st='git st'
alias ci='git ci'
alias lg='git log'
alias co='git co'
alias br='git branch'
alias dc='git diff --cached'

alias add='git add --all'
alias log='git log'
alias push='git push'
alias pull='git pull'
alias stash='git stash'
alias clone='git clone'
alias fetch='git fetch'
alias merge='git merge -s recursive -X patience'
alias branch='git branch'
alias rebase='git rebase'
alias amend='git commit -C HEAD --amend'

alias up="git up"

# Enable grouping directories if available
if ls --grop-directories-first 2> /dev/null; then
  alias ls="ls --group-directories-first --color=tty --ignore node_modules"
else
  alias ls="ls --color=tty --ignore node_modules"
fi
