#!/usr/bin/env zsh
set -E

e_header()   { echo -e "\n\033[1m$@\033[0m"; }
e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
e_arrow()    { echo -e " \033[1;33m➜\033[0m  $@"; }

if test -e "$1"; then
  DOTHOME="$(cd "$1" && pwd -P)"
else
  echo "Usage: dotfiles DOTHOME"
fi

BACKDIR="$HOME/.backup/dotfiles/$(date "+%Y_%m_%d-%H_%M_%S")/"

run() {
  ensure_git
  get_dotfiles
  link_dotfiles
  print_messages
}

ensure_git() {
  if [[ -z $commands[git] && "$OSTYPE" =~ ^darwin ]]; then
    if [[ -n $commands[brew] ]]; then
      e_header "Installing Homebrew..."
      ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
    fi

    if [[ -n $commands[brew] ]]; then
      e_header "Updating Homebrew..."
      brew update
      e_header "Installing Git..."
      brew install git
    fi
  fi

  # If Git isn't installed by now, something exploded. 
  if [[ -z $commands[git] ]]; then
    e_error "Git should be installed. It isn't. Aborting."
    exit 1
  fi
}

get_dotfiles() {
  e_header "Updating dotfiles..."
  cd $DOTHOME && git pull
}

link_dotfiles() {
  e_header "Linking files into home directory..."

  cd "$HOME"
  for file in $DOTHOME/.*; do
    local base="$(basename $file)"
    local dest="$HOME/$base"

    # Don't link .git directory
    if test "$base" = ".git"; then
      continue;
    fi 

    # Skip if link is the same.
    if test "$file" -ef "$dest"; then
      e_success "$base"
      continue
    fi

    # Back up file if it exists.
    if [[ -e "$dest" ]]; then
      e_arrow "Backing up $HOME/$base."
      inform_about_backup=1
      mkdir -p "$BACKDIR"
      mv "$dest" "$BACKDIR"
    fi

    ln -sf "${file#$HOME/}" "$base"
    e_success "$base"
  done
}

print_messages() {
  if [[ $inform_about_backup == 1 ]]; then
    echo "\nBackups were moved to $BACKDIR\n"
  fi

  if [[ $first_run == 1 ]]; then
    echo "\nInstallation complete! You can relogin now."
  else
    echo # it's visually better ;)
  fi
}

(run)
