tap "homebrew/cask"
tap "homebrew/services"
tap "buo/cask-upgrade"

brew "zsh"
brew "coreutils"
brew "mas"

# Terminal
brew "vim"
brew "neovim"
brew "fzf"
brew "ripgrep"
brew "git"
brew "git-lfs"
brew "lazygit"
brew "htop"
brew "tmux"
brew "reattach-to-user-namespace"
brew "tree"
brew "jq"
brew "nnn"
brew "viu"
brew "ranger"
brew "entr"
brew "youtube-dl"
brew "curl"
brew "wget"
brew "nmap"
brew "mtr"

# Programming
brew "cmake"
brew "imagemagick"
brew "node"
brew "yarn"
brew "go"
brew "podman"
brew "rust"
brew "typescript"
brew "python@3.8"
brew "packer"
brew "podman"

# For backup
brew "restic"
brew "f3"

# For storage
brew "postgresql"
brew "postgis"
brew "redis"

# Chess
brew "lc0"
brew "stockfish"

# Network
brew "iperf"

# Apps
cask "android-studio"
cask "blender"
cask "caffeine"
cask "cyberduck"
cask "darktable"
cask "deezer"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "lulu"
cask "messenger"
cask "obs"
cask "openscad"
cask "parallels"
cask "postico"
cask "prusaslicer"
cask "raspberry-pi-imager"
cask "rhino"
cask "signal"
cask "spotify"
cask "steam"
cask "the-unarchiver"
cask "transmission"
cask "twitch"
cask "ultimaker-cura"
cask "vagrant"
cask "vlc"
cask "whatsapp"
cask "freecad"
cask "openscad"
cask "visual-studio-code"

#mas "Microsoft To Do", id: 1274495053
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
mas "Pages", id: 409201541
